# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-11-06 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0002_auto_20191105_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='artifacts/'),
        ),
    ]
