# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-11-06 10:35
from __future__ import unicode_literals

import artifacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0003_artifact_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=artifacts.models.upload_image_path),
        ),
    ]
