# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-11-06 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0005_auto_20191106_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='slug',
            field=models.SlugField(default='auction'),
            preserve_default=False,
        ),
    ]
