# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-11-06 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0006_artifact_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
