# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-11-26 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0009_auto_20191124_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
