# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-11-15 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifacts', '0007_auto_20191106_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('artifacts', models.ManyToManyField(blank=True, to='artifacts.Artifact')),
            ],
        ),
    ]
